---
title:               Red Protoss
tagline:             Buddy Magsipoc
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Cakey
twitter:             keikun17
github:              keikun17
# email:               address@example.com
# google_analytics_id: YOUR_GA_ID
